const links = {
    "northAmerica": [
        "https://www.youtube.com/watch?v=MAVfqeTLN94",
        "https://www.youtube.com/watch?v=FliLpEcYyeE",
        "https://www.youtube.com/watch?v=Nk6-M7v0y10",
        "https://www.youtube.com/watch?v=XaGZKuc0G4k",
        "https://www.youtube.com/watch?v=bOAuG0MAlOg",
        "https://www.youtube.com/watch?v=RY_NrjMUGfk",
        "https://www.youtube.com/watch?v=GAMoMFiTqtk",
        "https://www.youtube.com/watch?v=09Ui0F-tIVs",
        "https://www.youtube.com/watch?v=gIK8AMa4KDc",
        "https://www.youtube.com/watch?v=9358a-8eUXs",
        "https://www.youtube.com/watch?v=qJu6tDZmwds",
        "https://www.youtube.com/watch?v=3ju1MuBNCHg",
        "https://www.youtube.com/watch?v=pCn6_vMYUos",
        "https://youtu.be/UvIJmoMjI9c?t=65",
        "https://youtu.be/t_x2ey2IDDk?t=14",
        "https://youtu.be/I0Mcg1OO8yE?t=22",
        "https://www.youtube.com/watch?v=7x7fsPEivPU",
        "https://www.youtube.com/watch?v=wUoSbETkS2Q",
        "https://youtu.be/-_OzymdJ03c?t=105",
        "https://www.youtube.com/watch?v=40TA9OkML2k",
        "https://www.youtube.com/watch?v=jKE5Nv9CQwI",
        "https://youtu.be/B9SpZOP5UbQ"

    ],
    "latinAmerica": [
        "https://youtu.be/NkdUs2Dxv4s?t=17",
        "https://youtu.be/8IObz87Be9Q",
        "https://youtu.be/ihecR8gt0WE",
        "https://youtu.be/ah95W85hb5g",
        "https://www.youtube.com/watch?v=JWe9IigF5SU&ab_channel=BreakThroughNews",
        "https://www.youtube.com/watch?v=BEQWy8LLO88",
        "https://www.youtube.com/watch?v=qYxHx3OsD88",
        "https://www.youtube.com/watch?v=JvPE8jifIV0",
        "https://www.youtube.com/watch?v=n_o3u17HtAg",
        "https://www.youtube.com/watch?v=YcAqrRXRluU",
        "https://youtu.be/c4iTedP-7Ek?t=49",
        "https://www.youtube.com/watch?v=BKykW7gRFjc",
        "https://www.youtube.com/watch?v=FYM4eHH_oDw",
        "https://www.youtube.com/watch?v=KmgRXXNvokE",
        "https://www.youtube.com/watch?v=SEnehFGA6Gg",
        "https://www.youtube.com/watch?v=hUoqt5Goa1w"


    ],
    "europe": [
        "https://www.youtube.com/watch?v=IbdCaaW2cDc",
        "https://www.youtube.com/watch?v=ChrOpdAr7fY",
        "https://www.youtube.com/watch?v=DkAb7SmH-PY",
        "https://www.youtube.com/watch?v=pbixAzhDLrU",
        "https://youtu.be/qQUZf161raI",
        "https://www.youtube.com/watch?v=N__aBAGEFdk",
        "https://www.youtube.com/watch?v=37wCScaWO8Q",
        "https://www.youtube.com/watch?v=_TJz-uSZs60",
        "https://www.youtube.com/watch?v=Zthl4OvwE04&list=PLCUKIeZnrIUmLL9IWxWPo2OXYPk-xtDdO&index=41",
        "https://www.youtube.com/watch?v=JJlHcXxuj-4&list=PLCUKIeZnrIUmLL9IWxWPo2OXYPk-xtDdO&index=71",
        "https://www.youtube.com/watch?v=LHSsFqpd2ns&list=PLT6yxVwBEbi0Q8wAkcLl8el1T3LLM41Yq&index=89",
        "https://www.youtube.com/watch?v=n128SW1qPEM&list=PLT6yxVwBEbi0Q8wAkcLl8el1T3LLM41Yq&index=99",
        "https://www.youtube.com/watch?v=INX_3MiLB0s&list=PLT6yxVwBEbi0Q8wAkcLl8el1T3LLM41Yq&index=109",
        "https://www.youtube.com/watch?v=gIc0j9qUVAY",
        "https://youtu.be/Gi3Pq8iMasA",
        "https://youtu.be/zglTBGKgD3M",
        "https://youtu.be/pwga_ivwKLo",
        "https://www.youtube.com/watch?v=q5M7w8IjZM0"

    ],
    "africa":[
        "https://youtu.be/YayRpW-bl6Q",
        "https://youtu.be/KWMGoT3C5BE",
        "https://youtu.be/6vu16c2eSWs",
        "https://youtu.be/dSbl7JR2Dz8",
        "https://youtu.be/L9HB9spSQS8",
        "https://youtu.be/Ynhx-BF0XMU",
        "https://youtu.be/QMo1SnXHa3M",
        "https://www.youtube.com/watch?v=D25NrAQZLng",
        "https://www.youtube.com/watch?v=Yh6wHvJqVsk",
        "https://www.youtube.com/watch?v=P4gIqQ4TZlc",
        "https://www.youtube.com/watch?v=P4gIqQ4TZlc",
        "https://www.youtube.com/watch?v=3kCrz9bx9U4",
        "https://www.youtube.com/watch?v=nLxE3O5Ilz4",
        "https://www.youtube.com/watch?v=wnQhT-A3z-k",
        "https://www.youtube.com/watch?v=c3PTEIu0TAU"

    ],
    "middleEast":[
        "https://youtu.be/elAEZNYpOlM",
        "https://www.youtube.com/watch?v=_NBr1meMjLU&ab_channel=PakistanObserver",
        "https://www.youtube.com/watch?v=0yJwGD4ic-c&t=16s",
        "https://www.youtube.com/watch?v=hhrLBNgKDP8",
        "https://youtu.be/lnOvOL8H77M?t=4",
        "https://youtu.be/VK6GklJKKyA",
        "https://www.youtube.com/watch?v=H83SkT6m63o",
        "https://youtu.be/5fsKZJPWImM",
        "https://youtu.be/0yJwGD4ic-c?t=16",
        "https://www.youtube.com/watch?v=FDxTHzY8aNo",
        "https://www.youtube.com/watch?v=mh62wJEaXAM",
        "https://www.youtube.com/watch?v=6jx0FWU7Sm4",
        "https://www.youtube.com/watch?v=P8IJz7lE22A",
        "https://www.youtube.com/watch?v=sqzhw-Takx8",
        "https://www.youtube.com/watch?v=9yV0I1ojUJw",
        "https://www.youtube.com/watch?v=XfDPUWfgTWo",
        "https://www.youtube.com/watch?v=tQhLQhHTXB0",
        "https://www.youtube.com/watch?v=m5uPqdevcc4",
        "https://www.youtube.com/watch?v=Vx3NBiQhQxQ"


    ],
    "eastAsia":[
        "https://youtu.be/OAIOfxaM7JY", 
        "https://youtu.be/royL8uvTQQ8?t=19", 
        "https://youtu.be/4V0axkRv9Q0", 
        "https://youtu.be/8eSktqEH6u4", 
        "https://youtu.be/3gMNoZ0yV14",
        "https://www.youtube.com/watch?v=-jQc3yl8VWg",
        "https://www.youtube.com/watch?v=kufVQX7rUGU",
        "https://www.youtube.com/watch?v=vEgE4R_6fLU&ab_channel=KOREANOW",
        "https://www.youtube.com/watch?v=4qdtQYUa2xQ",
        "https://www.youtube.com/watch?v=hRptIyKLfc0",
        "https://www.youtube.com/watch?v=S1VG1m_9zbM",
        "https://www.youtube.com/watch?v=hUoqt5Goa1w",
        "https://www.youtube.com/watch?v=GYIK_bRf9WI",
        "https://www.youtube.com/watch?v=2mxocMgUrvo"

    ]
}